### ISSUE TITLE
place의 category 값으로 story fitler

### ISSUE THREAD

**Issue by lina1919** [sdp-tech/SASM_BE#118]
## Description
-  `raise FieldError("Cannot resolve keyword '%s' into field. "`
-` query = Q(category=a)` 에서 story object에 category가 없기 때문에 에러 발생

**Comment by lina1919** [comment]
[](https://stackoverflow.com/questions/11508744/django-models-filter-by-foreignkey)
필드 명을 지정해주어야 한다.

**Comment by yxnxx** [comment]
https://kimdoky.github.io/django/2018/05/10/django-Related-Field-icontains/
해당 모델의 어떤 필드인지 지정해야 한다.
