### ISSUE TITLE
Place admin create, update

### ISSUE THREAD

**Issue by yew00n** [sdp-tech/SASM_BE#150]
## Description
- 장소 데이터 입력받아 위경도 값 추출 및 db에 저장
- 기존에 존재하는 장소이면 데이터 업데이트 
- 장소 이름이 이미 존재하는지 확인하는 부수적인 API 추가(Front쪽 이름 중복 체크용)

## ETC
- rep_pic 경로 설정
- query set index로 pic1, pic2, pic3 save, update가 안됨: id로 object를 반환해서 성공!

**Comment by lina1919** [comment]
수정하는 경우 placephoto나 rep_pic에 대한 파일 자체를 모두 줄 수 없음
따라서 어떤 값이 수정되었는지 파악 -> 값 적용!
