### ISSUE TITLE
simple_jwt CORS issue

### ISSUE THREAD

**Issue by yxnxx** [sdp-tech/SASM_BE#170]
## Description
- `access to xmlhttprequest at 'http://127.0.0.1:8000/users/token/refresh/' from origin 'http://localhost:3000' has been blocked by cors policy: request header field refresh is not allowed by access-control-allow-headers in preflight response.`
Refresh Token으로 Access Token을 재발급 받을 때, CORS issue 발생. 
`const rr = await axios.post(
        "http://127.0.0.1:8000/users/token/refresh/",
        {
          headers: {
            Refresh: refreshtoken,
          },
        }
      );`
headers로 보내는 필드 이름이 없어서 CORS 오류가 난 것 같음.

**Comment by lina1919** [comment]
**FE CODE**
`      const rr = await axios.post(
        "http://127.0.0.1:8000/users/token/refresh/",
        {
          refresh: refreshtoken,
        },
        {
          headers: {
            Authorization: "No Auth",
          },
        }
      );`
BE의 exception custom 에서도 문제였던 듯!
django에서 내는 error가 아니어서 형식이 달라서 변경함
