### ISSUE TITLE
save_place 에서만 CORS 이슈 발생

### ISSUE THREAD

**Issue by lina1919** [sdp-tech/SASM_BE#200]
## Description
- 장소를 생성하는 places/save_place 에서만 cors issue가 발생
- post에서만 그런가 싶어서 좋아요 눌러서 확인해봤는데 좋아요는 잘 작동함

## To-Do
- [ ] CORS_ORIGIN_WHITELIST를 CORS_ALLOW_ORIGIN으로 바꾸기
- [ ] sasm.co.kr의 위치를 리스트의 맨 앞으로 옮기기

## ETC
진짜 요상한 에러...

**Comment by sejongk** [comment]
오류 원인: save_place에서 1MB 이상의 이미지 업로드 시 nginx에서 '413 Request Entity Too Large' 에러를 반환, nginx에서 즉각 오류를 리턴하므로 응답에 Access-Control-Allow-Origin이 제대로 설정되지 않아 CORS 오류 발생

해결 방안: nginx.conf에서 client_max_body_size를 10MB로 증가시킴, 업데이트된 nginx.conf 파일을 담은 nginx 컨테이너 이미지 재빌드 및 실행
