### ISSUE TITLE
story view 조회수 방지 적용

### ISSUE THREAD

**Issue by lina1919** [sdp-tech/SASM_BE#73]
## Description
- 쿠키를 활용한 story view에 조회수 방지가 적용되지 않고있다.

## To-Do
- [ ] cookie code를 다시 봐본다.
- [ ] story_list code를 다시 본다.

**Comment by lina1919** [comment]
[https://stackoverflow.com/questions/61796996/what-is-difference-between-self-get-serializer-and-serializer-object-in-django-r](url)
`#object와 queryset 나누기
 detail_story = get_object_or_404(self.get_queryset(),pk=id)
 story = self.get_queryset().filter(pk=id)`
`        #get_serializer은 queryset만 바꿈
        serializer = self.get_serializer(story, many=True, context={'request': request})`

**Comment by sejongk** [comment]
문제 상황: 될 때도 있고 안될 때도 있음
